"use client"
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { useState } from "react";
import Header from "./components/header";
import { MantineProvider, ColorSchemeScript } from "@mantine/core";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [colorScheme, setColorScheme] = useState("light"); // Default theme

  return (
    <html lang="en">
       <head>
        <ColorSchemeScript /> {/* Ensures dark/light mode persists */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

    <MantineProvider theme={{ colorScheme }} defaultColorScheme="auto">
          <Header />
          {children}
   </MantineProvider>
      </body>
    </html>
  );
}
